// <auto-generated />
using System;
using AAA_API.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AAA_API.Migrations
{
    [DbContext(typeof(Gambling_AppContext))]
    partial class Gambling_AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AAA_API.Models.TblConfirmLeague", b =>
                {
                    b.Property<decimal>("ConfirmLeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("confirmLeagueId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LeagueId")
                        .HasColumnName("leagueId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("RapidLeagueId")
                        .HasColumnName("rapidLeagueId")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ConfirmLeagueId");

                    b.ToTable("tbl_confirmLeague");
                });

            modelBuilder.Entity("AAA_API.Models.TblCredit", b =>
                {
                    b.Property<decimal>("CreditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("creditId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<int?>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CreatedBy")
                        .HasColumnName("createdBy")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PostingNo")
                        .HasColumnName("postingNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("UserId")
                        .HasColumnName("userId")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("CreditId")
                        .HasName("PK_tbl_Credit");

                    b.ToTable("tbl_credit");
                });

            modelBuilder.Entity("AAA_API.Models.TblFootballTeam", b =>
                {
                    b.Property<decimal>("FootballTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("footballTeamId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CreatedBy")
                        .HasColumnName("createdBy")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FootballTeam")
                        .HasColumnName("footballTeam")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FootballTeamMyan")
                        .HasColumnName("footballTeamMyan")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("LeagueId")
                        .HasColumnName("leagueId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("RapidTeamId")
                        .HasColumnName("rapidTeamId")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("FootballTeamId");

                    b.ToTable("tbl_footballTeam");
                });

            modelBuilder.Entity("AAA_API.Models.TblGambling", b =>
                {
                    b.Property<decimal>("GamblingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gamblingId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<int?>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("int");

                    b.Property<decimal?>("EventId")
                        .HasColumnName("eventId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("GamblingTypeId")
                        .HasColumnName("gamblingTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PostingNo")
                        .HasColumnName("postingNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("RapidEventId")
                        .HasColumnName("rapidEventId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("TeamCount")
                        .HasColumnName("teamCount")
                        .HasColumnType("int");

                    b.HasKey("GamblingId")
                        .HasName("PK_tbl_singleGambling");

                    b.ToTable("tbl_gambling");
                });

            modelBuilder.Entity("AAA_API.Models.TblGamblingDetails", b =>
                {
                    b.Property<decimal>("GamblingDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gamblingDetailsId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("FootballTeamId")
                        .HasColumnName("footballTeamId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("GamblingId")
                        .HasColumnName("gamblingId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("LeagueId")
                        .HasColumnName("leagueId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("Overs")
                        .HasColumnName("overs")
                        .HasColumnType("bit");

                    b.Property<bool?>("Under")
                        .HasColumnName("under")
                        .HasColumnType("bit");

                    b.HasKey("GamblingDetailsId");

                    b.ToTable("tbl_gamblingDetails");
                });

            modelBuilder.Entity("AAA_API.Models.TblGamblingType", b =>
                {
                    b.Property<int>("GamblingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gamblingTypeId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GamblingType")
                        .HasColumnName("gamblingType")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("GamblingTypeId");

                    b.ToTable("tbl_gamblingType");
                });

            modelBuilder.Entity("AAA_API.Models.TblGamblingWin", b =>
                {
                    b.Property<decimal>("GamblingWinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gamblingWinId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("GamblingId")
                        .HasColumnName("gamblingId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("GamblingTypeId")
                        .HasColumnName("gamblingTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("GoalResultId")
                        .HasColumnName("goalResultId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("UserId")
                        .HasColumnName("userId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("WinAmount")
                        .HasColumnName("winAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("GamblingWinId");

                    b.ToTable("tbl_gamblingWin");
                });

            modelBuilder.Entity("AAA_API.Models.TblGoalResult", b =>
                {
                    b.Property<decimal>("GoalResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("goalResultId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AwayResult")
                        .HasColumnName("awayResult")
                        .HasColumnType("int");

                    b.Property<int?>("HomeResult")
                        .HasColumnName("homeResult")
                        .HasColumnType("int");

                    b.Property<string>("RapidEventId")
                        .HasColumnName("rapidEventId")
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.HasKey("GoalResultId");

                    b.ToTable("tbl_goalResult");
                });

            modelBuilder.Entity("AAA_API.Models.TblHandicap", b =>
                {
                    b.Property<decimal>("HandicapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("handicapId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AwayHandicap")
                        .HasColumnName("awayHandicap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("AwayOdd")
                        .HasColumnName("awayOdd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("EventDatetime")
                        .HasColumnName("eventDatetime")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("HomeHandicap")
                        .HasColumnName("homeHandicap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("HomeOdd")
                        .HasColumnName("homeOdd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("RapidEventId")
                        .HasColumnName("rapidEventId")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("HandicapId");

                    b.ToTable("tbl_handicap");
                });

            modelBuilder.Entity("AAA_API.Models.TblLeague", b =>
                {
                    b.Property<decimal>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("leagueId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<string>("LeagueName")
                        .HasColumnName("leagueName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("RapidLeagueId")
                        .HasColumnName("rapidLeagueId")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("LeagueId");

                    b.ToTable("tbl_league");
                });

            modelBuilder.Entity("AAA_API.Models.TblPreUpcomingEvent", b =>
                {
                    b.Property<decimal>("PreUpcommingEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("preUpcommingEventId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("AwayTeamId")
                        .HasColumnName("awayTeamId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnName("eventDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EventTime")
                        .HasColumnName("eventTime")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("HomeTeamId")
                        .HasColumnName("homeTeamId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("LeagueId")
                        .HasColumnName("leagueId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("RapidEventId")
                        .HasColumnName("rapidEventId")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("PreUpcommingEventId");

                    b.ToTable("tbl_preUpcomingEvent");
                });

            modelBuilder.Entity("AAA_API.Models.TblRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("roleId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CreatedBy")
                        .HasColumnName("createdBy")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Discription")
                        .HasColumnName("discription")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Role")
                        .HasColumnName("role")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("RoleId");

                    b.ToTable("tbl_role");
                });

            modelBuilder.Entity("AAA_API.Models.TblUpcomingEvent", b =>
                {
                    b.Property<decimal>("UpcomingEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("upcomingEventId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("AwayTeamId")
                        .HasColumnName("awayTeamId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnName("eventDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EventTime")
                        .HasColumnName("eventTime")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("HomeTeamId")
                        .HasColumnName("homeTeamId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("LeagueId")
                        .HasColumnName("leagueId")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("RapidEventId")
                        .HasColumnName("rapidEventId")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("UpcomingEventId")
                        .HasName("PK_tbl_upComingEvent");

                    b.ToTable("tbl_upcomingEvent");
                });

            modelBuilder.Entity("AAA_API.Models.TblUser", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("userId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("BetLimitForMix")
                        .HasColumnName("betLimitForMix")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("BetLimitForSingle")
                        .HasColumnName("betLimitForSingle")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("CreatedBy")
                        .HasColumnName("createdBy")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("createdDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Lock")
                        .HasColumnName("lock")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MixBetCommission10count25")
                        .HasColumnName("mixBetCommission10count25")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MixBetCommission11count25")
                        .HasColumnName("mixBetCommission11count25")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MixBetCommission2count15")
                        .HasColumnName("mixBetCommission2count15")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MixBetCommission3count20")
                        .HasColumnName("mixBetCommission3count20")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MixBetCommission4count20")
                        .HasColumnName("mixBetCommission4count20")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MixBetCommission5count20")
                        .HasColumnName("mixBetCommission5count20")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MixBetCommission6count20")
                        .HasColumnName("mixBetCommission6count20")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MixBetCommission7count20")
                        .HasColumnName("mixBetCommission7count20")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MixBetCommission8count20")
                        .HasColumnName("mixBetCommission8count20")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MixBetCommission9count25")
                        .HasColumnName("mixBetCommission9count25")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Mobile")
                        .HasColumnName("mobile")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("RoleId")
                        .HasColumnName("roleId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SharePercent")
                        .HasColumnName("sharePercent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SingleBetCommission5")
                        .HasColumnName("singleBetCommission5")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SingleBetCommission8")
                        .HasColumnName("singleBetCommission8")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("UserId");

                    b.ToTable("tbl_user");
                });

            modelBuilder.Entity("AAA_API.Models.TblUserBalance", b =>
                {
                    b.Property<decimal>("UserBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("userBalanceId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Inward")
                        .HasColumnName("inward")
                        .HasColumnType("int");

                    b.Property<int?>("Outward")
                        .HasColumnName("outward")
                        .HasColumnType("int");

                    b.Property<string>("PostingNo")
                        .HasColumnName("postingNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("UserId")
                        .HasColumnName("userId")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("UserBalanceId");

                    b.ToTable("tbl_userBalance");
                });

            modelBuilder.Entity("AAA_API.Models.TblUserPosting", b =>
                {
                    b.Property<decimal>("UserPostingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("userPostingId")
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CreatedBy")
                        .HasColumnName("createdBy")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("createdDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Inward")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Outward")
                        .HasColumnName("outward")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PostingNo")
                        .HasColumnName("postingNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("UserId")
                        .HasColumnName("userId")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("UserPostingId");

                    b.ToTable("tbl_userPosting");
                });
#pragma warning restore 612, 618
        }
    }
}
